language: node_js
node_js:
  - "12"

git:
  depth: 1

jobs:
  include:
    - stage: "test"
      script: npm test
    - stage: "build"
      script: npm run build
    - stage: "install"
      script: npm install
    - stage: "deploy"
      script: skip
      deploy: 
        provider: heroku
        api_key:
          secure: HEROKU_API_KEY


#install: npm install
#script: npm run build
#deploy:

stages:
  - install
  - name: test
    if: branch = master
  - build
  - name: deploy
    if: branch = master