export const UPDATE_FEEDS_LIST = 'FEEDS_FETCHED';
export const UPDATE_FEEDS_PAGINATION = 'UPDATE_FEEDS_PAGINATION';
export const UPVOTE_FEED = 'UPVOTE_FEED';
export const FEED_FETCH_ERROR = 'FEED_FETCH_ERROR';